options:
    prevLabel: '<'
    nextLabel: '>'
    doneLabel: '&#10003;'
    exitOnOverlayClick: false
    exitOnEsc: false
    disableInteraction: true
    tooltipClass: w3-theme-l3
tours:
    index:
        steps:
            nav:
                element: '#navigation-bar'
            feedback: 
                element: '#feedback'
        next_page: storage.html
    storage:
        steps:
            create:
                element: '#create'
            items:
                element: '#items'
        next_page: shop.html
    shop: 
        steps:
            products:
                element: '#products'
            itembag:
                element: '#itembag'
            pay:
                element: '#pay'
        next_page: about.html
    about:
        steps:
            startIntro:
                element: '#startIntro'
                